import Head from "next/head";
import { Inter } from "next/font/google";
import Quotes from "@/components/Quotes";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Shayan Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col justify-start items-center gap-20">
        <h1 className="text-3xl font-bold text-center mt-5">
          Welcome to my Quotes world!
        </h1>
        <Quotes />
      </main>
    </>
  );
}
